CREATE TABLE tracks_points (
	id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	trackid INTEGER,
	num INTEGER,
	lat REAL NOT NULL, lng REAL NOT NULL,
	datetime TEXT,
	ele REAL,
	distance REAL,
	showonmap INTEGER,
	FOREIGN KEY (trackid) REFERENCES tracks (id)
	ON DELETE CASCADE
	ON UPDATE CASCADE
);