//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TileExplorer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TileExplorer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файл должен находиться в каталоге c номером версии, например, {0}..
        /// </summary>
        internal static string AppUpdateErrorFileWrongLocation {
            get {
                return ResourceManager.GetString("AppUpdateErrorFileWrongLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось проверить или установить обновление.
        ///Ошибка:
        ///{0}..
        /// </summary>
        internal static string AppUpdateErrorInProgress {
            get {
                return ResourceManager.GetString("AppUpdateErrorInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Установлена актуальная версия..
        /// </summary>
        internal static string AppUpdateInfoAlreadyLatest {
            get {
                return ResourceManager.GetString("AppUpdateInfoAlreadyLatest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Процесс обновления уже запущен..
        /// </summary>
        internal static string AppUpdateInfoInProgress {
            get {
                return ResourceManager.GetString("AppUpdateInfoInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поиск обновления.
        /// </summary>
        internal static string AppUpdateInfoStatusCheckLatest {
            get {
                return ResourceManager.GetString("AppUpdateInfoStatusCheckLatest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузка обновления.
        /// </summary>
        internal static string AppUpdateInfoStatusDownload {
            get {
                return ResourceManager.GetString("AppUpdateInfoStatusDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Установка обновления.
        /// </summary>
        internal static string AppUpdateInfoStatusExtract {
            get {
                return ResourceManager.GetString("AppUpdateInfoStatusExtract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Происходит процесс обновления. Прервать?.
        /// </summary>
        internal static string AppUpdateQuestionInProgress {
            get {
                return ResourceManager.GetString("AppUpdateQuestionInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Программа обновлена. Перезапустить для применения обновления?.
        /// </summary>
        internal static string AppUpdateQuestionUpdated {
            get {
                return ResourceManager.GetString("AppUpdateQuestionUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Архив не содержит снаряжение..
        /// </summary>
        internal static string BackupErrorFileEquipmentsNotExists {
            get {
                return ResourceManager.GetString("BackupErrorFileEquipmentsNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Архив не содержит маркеры..
        /// </summary>
        internal static string BackupErrorFileMarkersNotExists {
            get {
                return ResourceManager.GetString("BackupErrorFileMarkersNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Архив содержит данные. Заменить?.
        /// </summary>
        internal static string BackupErrorFilesExists {
            get {
                return ResourceManager.GetString("BackupErrorFilesExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Архив не содержит данные о треках..
        /// </summary>
        internal static string BackupErrorFileTrackExtsNotExists {
            get {
                return ResourceManager.GetString("BackupErrorFileTrackExtsNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не указан архив..
        /// </summary>
        internal static string BackupErrorNameEmpty {
            get {
                return ResourceManager.GetString("BackupErrorNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не выбраны данные для восстановления..
        /// </summary>
        internal static string BackupErrorNothingLoad {
            get {
                return ResourceManager.GetString("BackupErrorNothingLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не выбраны данные для архивирования..
        /// </summary>
        internal static string BackupErrorNothingSave {
            get {
                return ResourceManager.GetString("BackupErrorNothingSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Процесс архивации уже запущен..
        /// </summary>
        internal static string BackupInfoInProgress {
            get {
                return ResourceManager.GetString("BackupInfoInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось прочитать архив.
        ///Ошибка:
        ///{0}..
        /// </summary>
        internal static string BackupLoadFail {
            get {
                return ResourceManager.GetString("BackupLoadFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Данные из архива &apos;{0}&apos; загружены..
        /// </summary>
        internal static string BackupLoadOk {
            get {
                return ResourceManager.GetString("BackupLoadOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось сохранить архив.
        ///Ошибка:
        ///{0}..
        /// </summary>
        internal static string BackupSaveFail {
            get {
                return ResourceManager.GetString("BackupSaveFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Архив сохранён в &apos;{0}&apos;..
        /// </summary>
        internal static string BackupSaveOk {
            get {
                return ResourceManager.GetString("BackupSaveOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Каталог с базой данных «{0}» не существует.
        ///Установить расположение по умолчанию «{1}»?
        ///
        ///Отказ приведёт к закрытию приложения..
        /// </summary>
        internal static string ErrorDatabaseDirectoryNotExists {
            get {
                return ResourceManager.GetString("ErrorDatabaseDirectoryNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Каталог «{0}» не существует..
        /// </summary>
        internal static string ErrorDirectoryNotExists {
            get {
                return ResourceManager.GetString("ErrorDirectoryNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Каталог с треками не указан..
        /// </summary>
        internal static string ErrorDirectoryTracksEmpty {
            get {
                return ResourceManager.GetString("ErrorDirectoryTracksEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Каталог «{0}» не может располагаться в указанном месте..
        /// </summary>
        internal static string ErrorDirectoryWrongLocation {
            get {
                return ResourceManager.GetString("ErrorDirectoryWrongLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Необходимо ввести число..
        /// </summary>
        internal static string ErrorNeedDigit {
            get {
                return ResourceManager.GetString("ErrorNeedDigit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Необходимо указать значение..
        /// </summary>
        internal static string ErrorNeedText {
            get {
                return ResourceManager.GetString("ErrorNeedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Во время запуска произошла ошибка:
        ///{0}.
        /// </summary>
        internal static string ErrorOpenPath {
            get {
                return ResourceManager.GetString("ErrorOpenPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gpx.
        /// </summary>
        internal static string FileSaveDefaultExtGpx {
            get {
                return ResourceManager.GetString("FileSaveDefaultExtGpx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to osm.
        /// </summary>
        internal static string FileSaveDefaultExtOsm {
            get {
                return ResourceManager.GetString("FileSaveDefaultExtOsm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to png.
        /// </summary>
        internal static string FileSaveDefaultExtPng {
            get {
                return ResourceManager.GetString("FileSaveDefaultExtPng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPX|*.gpx|Все файлы|*.*.
        /// </summary>
        internal static string FileSaveFilterGpx {
            get {
                return ResourceManager.GetString("FileSaveFilterGpx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OSM|*.osm|Все файлы|*.*.
        /// </summary>
        internal static string FileSaveFilterOsm {
            get {
                return ResourceManager.GetString("FileSaveFilterOsm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PNG|*.png|Все файлы|*.*.
        /// </summary>
        internal static string FileSaveFilterPng {
            get {
                return ResourceManager.GetString("FileSaveFilterPng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/P3tr0viCh/TileExplorer.
        /// </summary>
        internal static string GitHubLink {
            get {
                return ResourceManager.GetString("GitHubLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Во время поиска новых треков произошла ошибка:
        ///{0}..
        /// </summary>
        internal static string MsgCheckDirectoryTracksFail {
            get {
                return ResourceManager.GetString("MsgCheckDirectoryTracksFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось загрузить результаты трека.
        ///Ошибка:
        ///{0}..
        /// </summary>
        internal static string MsgDatabaseLoadChartTrackEleFail {
            get {
                return ResourceManager.GetString("MsgDatabaseLoadChartTrackEleFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось загрузить треки за месяц.
        ///Ошибка:
        ///{0}..
        /// </summary>
        internal static string MsgDatabaseLoadChartTracksByMonthFail {
            get {
                return ResourceManager.GetString("MsgDatabaseLoadChartTracksByMonthFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось загрузить треки за год.
        ///Ошибка:
        ///{0}..
        /// </summary>
        internal static string MsgDatabaseLoadChartTracksByYearFail {
            get {
                return ResourceManager.GetString("MsgDatabaseLoadChartTracksByYearFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось загрузить список снаряжения.
        ///Ошибка:
        ///{0}..
        /// </summary>
        internal static string MsgDatabaseLoadListEquipmentsFail {
            get {
                return ResourceManager.GetString("MsgDatabaseLoadListEquipmentsFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось загрузить список маркеров.
        ///Ошибка:
        ///{0}..
        /// </summary>
        internal static string MsgDatabaseLoadListMarkersFail {
            get {
                return ResourceManager.GetString("MsgDatabaseLoadListMarkersFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось загрузить результаты по снаряжению.
        ///Ошибка:
        ///{0}..
        /// </summary>
        internal static string MsgDatabaseLoadListResultEquipmentsFail {
            get {
                return ResourceManager.GetString("MsgDatabaseLoadListResultEquipmentsFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось загрузить результаты по годам.
        ///Ошибка:
        ///{0}..
        /// </summary>
        internal static string MsgDatabaseLoadListResultYearsFail {
            get {
                return ResourceManager.GetString("MsgDatabaseLoadListResultYearsFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось загрузить информацию о плитке.
        ///Ошибка:
        ///{0}..
        /// </summary>
        internal static string MsgDatabaseLoadListTileInfoFail {
            get {
                return ResourceManager.GetString("MsgDatabaseLoadListTileInfoFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось загрузить список треков.
        ///Ошибка:
        ///{0}..
        /// </summary>
        internal static string MsgDatabaseLoadListTrackFail {
            get {
                return ResourceManager.GetString("MsgDatabaseLoadListTrackFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось загрузить плитки.
        ///Ошибка:
        ///{0}..
        /// </summary>
        internal static string MsgDatabaseLoadTilesFail {
            get {
                return ResourceManager.GetString("MsgDatabaseLoadTilesFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось загрузить треки по месяцам.
        ///Ошибка:
        ///{0}..
        /// </summary>
        internal static string MsgDatabaseLoadTracksTreeFail {
            get {
                return ResourceManager.GetString("MsgDatabaseLoadTracksTreeFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новые треки в каталоге «{0}» не найдены..
        /// </summary>
        internal static string MsgDirectoryTracksNoNewFiles {
            get {
                return ResourceManager.GetString("MsgDirectoryTracksNoNewFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Плитка не открыта..
        /// </summary>
        internal static string MsgTileNotVisited {
            get {
                return ResourceManager.GetString("MsgTileNotVisited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.openstreetmap.org/edit#map={0}/{1}/{2}.
        /// </summary>
        internal static string OsmUrlEdit {
            get {
                return ResourceManager.GetString("OsmUrlEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.openstreetmap.org/#map={0}/{1}/{2}.
        /// </summary>
        internal static string OsmUrlOpen {
            get {
                return ResourceManager.GetString("OsmUrlOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обновление....
        /// </summary>
        internal static string ProgramStatusUpdating {
            get {
                return ResourceManager.GetString("ProgramStatusUpdating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить снаряжение «{0}»?.
        /// </summary>
        internal static string QuestionEquipmentDelete {
            get {
                return ResourceManager.GetString("QuestionEquipmentDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить снаряжение «{0}» и ещё {1}?.
        /// </summary>
        internal static string QuestionEquipmentsDelete {
            get {
                return ResourceManager.GetString("QuestionEquipmentsDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить домашнее расположение?.
        /// </summary>
        internal static string QuestionHomeSave {
            get {
                return ResourceManager.GetString("QuestionHomeSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить маркер «{0}»?.
        /// </summary>
        internal static string QuestionMarkerDelete {
            get {
                return ResourceManager.GetString("QuestionMarkerDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить маркер «{0}» и ещё {1}?.
        /// </summary>
        internal static string QuestionMarkersDelete {
            get {
                return ResourceManager.GetString("QuestionMarkersDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обнаружен новый трек:
        ///{0}
        ///
        ///Добавить в базу?.
        /// </summary>
        internal static string QuestionNewTrackFinded1 {
            get {
                return ResourceManager.GetString("QuestionNewTrackFinded1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обнаружены новые треки:
        ///{0}
        ///
        ///Добавить в базу?.
        /// </summary>
        internal static string QuestionNewTrackFinded2 {
            get {
                return ResourceManager.GetString("QuestionNewTrackFinded2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обнаружены новые треки:
        ///{0}
        ///и ещё {1}.
        ///
        ///Добавить в базу?.
        /// </summary>
        internal static string QuestionNewTrackFinded3 {
            get {
                return ResourceManager.GetString("QuestionNewTrackFinded3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Приблизить для редактирования?.
        /// </summary>
        internal static string QuestionOsmSetEditZoom {
            get {
                return ResourceManager.GetString("QuestionOsmSetEditZoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить трек «{0}»?.
        /// </summary>
        internal static string QuestionTrackDelete {
            get {
                return ResourceManager.GetString("QuestionTrackDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Остановить загрузку треков?.
        /// </summary>
        internal static string QuestionTracksCancelToAll {
            get {
                return ResourceManager.GetString("QuestionTracksCancelToAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить трек «{0}» и ещё {1}?.
        /// </summary>
        internal static string QuestionTracksDelete {
            get {
                return ResourceManager.GetString("QuestionTracksDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Использовать снаряжение для всех треков?.
        /// </summary>
        internal static string QuestionTracksOKToAll {
            get {
                return ResourceManager.GetString("QuestionTracksOKToAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество: {0}.
        /// </summary>
        internal static string StatusCount {
            get {
                return ResourceManager.GetString("StatusCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дистанция:  {0:F2}.
        /// </summary>
        internal static string StatusDistance {
            get {
                return ResourceManager.GetString("StatusDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Высота:  {0:F0}.
        /// </summary>
        internal static string StatusEle {
            get {
                return ResourceManager.GetString("StatusEle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подъём:  {0:F0}.
        /// </summary>
        internal static string StatusEleAscent {
            get {
                return ResourceManager.GetString("StatusEleAscent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Спуск:  {0:F0}.
        /// </summary>
        internal static string StatusEleDescent {
            get {
                return ResourceManager.GetString("StatusEleDescent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выделение.
        /// </summary>
        internal static string StatusIsSelection {
            get {
                return ResourceManager.GetString("StatusIsSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Курсор: {0:F6}, {1:F6}.
        /// </summary>
        internal static string StatusMousePosition {
            get {
                return ResourceManager.GetString("StatusMousePosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Центр: {0:F6}, {1:F6}.
        /// </summary>
        internal static string StatusPosition {
            get {
                return ResourceManager.GetString("StatusPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выделено: {0}.
        /// </summary>
        internal static string StatusSelectedCount {
            get {
                return ResourceManager.GetString("StatusSelectedCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Плитка: {0}x{1}.
        /// </summary>
        internal static string StatusTileId {
            get {
                return ResourceManager.GetString("StatusTileId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кластер: {0}.
        /// </summary>
        internal static string StatusTilesMaxCluster {
            get {
                return ResourceManager.GetString("StatusTilesMaxCluster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Квадрат: {0}.
        /// </summary>
        internal static string StatusTilesMaxSquare {
            get {
                return ResourceManager.GetString("StatusTilesMaxSquare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Открыто: {0}.
        /// </summary>
        internal static string StatusTilesVisited {
            get {
                return ResourceManager.GetString("StatusTilesVisited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Треки: {0}.
        /// </summary>
        internal static string StatusTracksCount {
            get {
                return ResourceManager.GetString("StatusTracksCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Расстояние: {0:F0}.
        /// </summary>
        internal static string StatusTracksDistance {
            get {
                return ResourceManager.GetString("StatusTracksDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Масштаб: {0}.
        /// </summary>
        internal static string StatusZoom {
            get {
                return ResourceManager.GetString("StatusZoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:0,} км.
        /// </summary>
        internal static string TextChartTrackEleAxisX {
            get {
                return ResourceManager.GetString("TextChartTrackEleAxisX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} м.
        /// </summary>
        internal static string TextChartTrackEleAxisY {
            get {
                return ResourceManager.GetString("TextChartTrackEleAxisY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to d
        ///ddd.
        /// </summary>
        internal static string TextChartTracksByMonthAxisX {
            get {
                return ResourceManager.GetString("TextChartTracksByMonthAxisX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:F0} км.
        /// </summary>
        internal static string TextChartTracksByMonthAxisY {
            get {
                return ResourceManager.GetString("TextChartTracksByMonthAxisY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:F2}.
        /// </summary>
        internal static string TextChartTracksByMonthYLabel {
            get {
                return ResourceManager.GetString("TextChartTracksByMonthYLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} дн, {1:F0} км.
        /// </summary>
        internal static string TextChartTracksByYearCounts {
            get {
                return ResourceManager.GetString("TextChartTracksByYearCounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to км.
        /// </summary>
        internal static string TextMapZoomRulerKM {
            get {
                return ResourceManager.GetString("TextMapZoomRulerKM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to м.
        /// </summary>
        internal static string TextMapZoomRulerM {
            get {
                return ResourceManager.GetString("TextMapZoomRulerM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Другое.
        /// </summary>
        internal static string TextOther {
            get {
                return ResourceManager.GetString("TextOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Итого.
        /// </summary>
        internal static string TextTotal {
            get {
                return ResourceManager.GetString("TextTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Все записи.
        /// </summary>
        internal static string TextTracksTreeAll {
            get {
                return ResourceManager.GetString("TextTracksTreeAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Архив: восстановление.
        /// </summary>
        internal static string TitleBackupLoad {
            get {
                return ResourceManager.GetString("TitleBackupLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Архив: сохранение.
        /// </summary>
        internal static string TitleBackupSave {
            get {
                return ResourceManager.GetString("TitleBackupSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Снаряжение.
        /// </summary>
        internal static string TitleListEquipments {
            get {
                return ResourceManager.GetString("TitleListEquipments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Маркеры.
        /// </summary>
        internal static string TitleListMarkers {
            get {
                return ResourceManager.GetString("TitleListMarkers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Итоги по снаряжению.
        /// </summary>
        internal static string TitleListResultEquipments {
            get {
                return ResourceManager.GetString("TitleListResultEquipments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Итоги по годам.
        /// </summary>
        internal static string TitleListResultYears {
            get {
                return ResourceManager.GetString("TitleListResultYears", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Треки.
        /// </summary>
        internal static string TitleListTracks {
            get {
                return ResourceManager.GetString("TitleListTracks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Треки за месяц.
        /// </summary>
        internal static string TitleTracksByMonth {
            get {
                return ResourceManager.GetString("TitleTracksByMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Треки за год.
        /// </summary>
        internal static string TitleTracksByYear {
            get {
                return ResourceManager.GetString("TitleTracksByYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Треки по месяцам.
        /// </summary>
        internal static string TitleTracksTree {
            get {
                return ResourceManager.GetString("TitleTracksTree", resourceCulture);
            }
        }
    }
}
