//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TileExplorer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TileExplorer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Каталог «{0}» не существует..
        /// </summary>
        internal static string ErrorDirectoryNotExists {
            get {
                return ResourceManager.GetString("ErrorDirectoryNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to osm.
        /// </summary>
        internal static string FileSaveDefaultExtOsm {
            get {
                return ResourceManager.GetString("FileSaveDefaultExtOsm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to png.
        /// </summary>
        internal static string FileSaveDefaultExtPng {
            get {
                return ResourceManager.GetString("FileSaveDefaultExtPng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OSM|*.osm|Все файлы|*.*.
        /// </summary>
        internal static string FileSaveFilterOsm {
            get {
                return ResourceManager.GetString("FileSaveFilterOsm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PNG|*.png|Все файлы|*.*.
        /// </summary>
        internal static string FileSaveFilterPng {
            get {
                return ResourceManager.GetString("FileSaveFilterPng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/P3tr0viCh/TileExplorer.
        /// </summary>
        internal static string GitHubLink {
            get {
                return ResourceManager.GetString("GitHubLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось загрузить список маркеров.
        ///Ошибка:
        ///{0}..
        /// </summary>
        internal static string MsgDatabaseLoadListMarkersFail {
            get {
                return ResourceManager.GetString("MsgDatabaseLoadListMarkersFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось загрузить результаты.
        ///Ошибка:
        ///{0}..
        /// </summary>
        internal static string MsgDatabaseLoadListResultsFail {
            get {
                return ResourceManager.GetString("MsgDatabaseLoadListResultsFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось загрузить список треков.
        ///Ошибка:
        ///{0}..
        /// </summary>
        internal static string MsgDatabaseLoadListTrackFail {
            get {
                return ResourceManager.GetString("MsgDatabaseLoadListTrackFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обновление....
        /// </summary>
        internal static string ProgramStatusUpdating {
            get {
                return ResourceManager.GetString("ProgramStatusUpdating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить маркер «{0}»?.
        /// </summary>
        internal static string QuestionMarkerDelete {
            get {
                return ResourceManager.GetString("QuestionMarkerDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить трек «{0}»?.
        /// </summary>
        internal static string QuestionTrackDelete {
            get {
                return ResourceManager.GetString("QuestionTrackDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Общее.
        /// </summary>
        internal static string SettingsCategoryCommon {
            get {
                return ResourceManager.GetString("SettingsCategoryCommon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Маркеры.
        /// </summary>
        internal static string SettingsCategoryDesignMarkers {
            get {
                return ResourceManager.GetString("SettingsCategoryDesignMarkers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Плитки.
        /// </summary>
        internal static string SettingsCategoryDesignTiles {
            get {
                return ResourceManager.GetString("SettingsCategoryDesignTiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Треки.
        /// </summary>
        internal static string SettingsCategoryDesignTracks {
            get {
                return ResourceManager.GetString("SettingsCategoryDesignTracks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Формат.
        /// </summary>
        internal static string SettingsCategoryFormat {
            get {
                return ResourceManager.GetString("SettingsCategoryFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OpenStreetMap.
        /// </summary>
        internal static string SettingsCategoryOsm {
            get {
                return ResourceManager.GetString("SettingsCategoryOsm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Курсор: {0:F6}, {1:F6}.
        /// </summary>
        internal static string StatusMousePosition {
            get {
                return ResourceManager.GetString("StatusMousePosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Центр: {0:F6}, {1:F6}.
        /// </summary>
        internal static string StatusPosition {
            get {
                return ResourceManager.GetString("StatusPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Плитка: {0}, {1}.
        /// </summary>
        internal static string StatusTileId {
            get {
                return ResourceManager.GetString("StatusTileId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кластер: {0}.
        /// </summary>
        internal static string StatusTilesMaxCluster {
            get {
                return ResourceManager.GetString("StatusTilesMaxCluster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Квадрат: {0}.
        /// </summary>
        internal static string StatusTilesMaxSquare {
            get {
                return ResourceManager.GetString("StatusTilesMaxSquare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Открыто: {0}.
        /// </summary>
        internal static string StatusTilesVisited {
            get {
                return ResourceManager.GetString("StatusTilesVisited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Треки: {0}.
        /// </summary>
        internal static string StatusTracksCount {
            get {
                return ResourceManager.GetString("StatusTracksCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Расстояние: {0:F0}.
        /// </summary>
        internal static string StatusTracksDistance {
            get {
                return ResourceManager.GetString("StatusTracksDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Масштаб: {0}.
        /// </summary>
        internal static string StatusZoom {
            get {
                return ResourceManager.GetString("StatusZoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Маркеры.
        /// </summary>
        internal static string TitleListMarkers {
            get {
                return ResourceManager.GetString("TitleListMarkers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Итоги.
        /// </summary>
        internal static string TitleListResults {
            get {
                return ResourceManager.GetString("TitleListResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Треки.
        /// </summary>
        internal static string TitleListTracks {
            get {
                return ResourceManager.GetString("TitleListTracks", resourceCulture);
            }
        }
    }
}
