//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TileExplorer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourcesSettings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourcesSettings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TileExplorer.Properties.ResourcesSettings", typeof(ResourcesSettings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Графики.
        /// </summary>
        internal static string Category_Chart {
            get {
                return ResourceManager.GetString("Category.Chart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Общее.
        /// </summary>
        internal static string Category_Common {
            get {
                return ResourceManager.GetString("Category.Common", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Маркеры.
        /// </summary>
        internal static string Category_DesignMarkers {
            get {
                return ResourceManager.GetString("Category.DesignMarkers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Плитки.
        /// </summary>
        internal static string Category_DesignTiles {
            get {
                return ResourceManager.GetString("Category.DesignTiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Треки.
        /// </summary>
        internal static string Category_DesignTracks {
            get {
                return ResourceManager.GetString("Category.DesignTracks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Каталоги.
        /// </summary>
        internal static string Category_Directories {
            get {
                return ResourceManager.GetString("Category.Directories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Формат.
        /// </summary>
        internal static string Category_Format {
            get {
                return ResourceManager.GetString("Category.Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ОпенСтритМап.
        /// </summary>
        internal static string Category_Osm {
            get {
                return ResourceManager.GetString("Category.Osm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файл статуса плиток.
        /// </summary>
        internal static string Category_TileStatus {
            get {
                return ResourceManager.GetString("Category.TileStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файл статуса плиток: Османд.
        /// </summary>
        internal static string Category_TileStatusOsmand {
            get {
                return ResourceManager.GetString("Category.TileStatusOsmand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цвет сетки.
        /// </summary>
        internal static string ColorChart_DisplayName {
            get {
                return ResourceManager.GetString("ColorChart.DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цвет осей.
        /// </summary>
        internal static string ColorChartAxis_DisplayName {
            get {
                return ResourceManager.GetString("ColorChartAxis.DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цвет линии отметки.
        /// </summary>
        internal static string ColorChartCursor_DisplayName {
            get {
                return ResourceManager.GetString("ColorChartCursor.DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цвет сетки.
        /// </summary>
        internal static string ColorChartGrid_DisplayName {
            get {
                return ResourceManager.GetString("ColorChartGrid.DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цвет графика.
        /// </summary>
        internal static string ColorChartSerial_DisplayName {
            get {
                return ResourceManager.GetString("ColorChartSerial.DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цвет графика: прозрачность.
        /// </summary>
        internal static string ColorChartSerialAlpha_DisplayName {
            get {
                return ResourceManager.GetString("ColorChartSerialAlpha.DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цвет текста значений.
        /// </summary>
        internal static string ColorChartText_Description {
            get {
                return ResourceManager.GetString("ColorChartText.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цвет текста.
        /// </summary>
        internal static string ColorChartText_DisplayName {
            get {
                return ResourceManager.GetString("ColorChartText.DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Треки за год: цвет графика.
        /// </summary>
        internal static string ColorChartTracksByYearSerial_DisplayName {
            get {
                return ResourceManager.GetString("ColorChartTracksByYearSerial.DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Треки за год: прозрачность графика.
        /// </summary>
        internal static string ColorChartTracksByYearSerialAlpha_DisplayName {
            get {
                return ResourceManager.GetString("ColorChartTracksByYearSerialAlpha.DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цвет фона маркера.
        /// </summary>
        internal static string ColorMarkerFill_Description {
            get {
                return ResourceManager.GetString("ColorMarkerFill.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фон.
        /// </summary>
        internal static string ColorMarkerFill_DisplayName {
            get {
                return ResourceManager.GetString("ColorMarkerFill.DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прозрачность фона маркера.
        /// </summary>
        internal static string ColorMarkerFillAlpha_Description {
            get {
                return ResourceManager.GetString("ColorMarkerFillAlpha.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прозрачность.
        /// </summary>
        internal static string ColorMarkerFillAlpha_DisplayName {
            get {
                return ResourceManager.GetString("ColorMarkerFillAlpha.DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цвет линий маркера.
        /// </summary>
        internal static string ColorMarkerLine_Description {
            get {
                return ResourceManager.GetString("ColorMarkerLine.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цвет линий.
        /// </summary>
        internal static string ColorMarkerLine_DisplayName {
            get {
                return ResourceManager.GetString("ColorMarkerLine.DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прозрачность линий маркера.
        /// </summary>
        internal static string ColorMarkerLineAlpha_Description {
            get {
                return ResourceManager.GetString("ColorMarkerLineAlpha.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прозрачность линий.
        /// </summary>
        internal static string ColorMarkerLineAlpha_DisplayName {
            get {
                return ResourceManager.GetString("ColorMarkerLineAlpha.DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цвет маркера позиции на треке.
        /// </summary>
        internal static string ColorMarkerPosition_Description {
            get {
                return ResourceManager.GetString("ColorMarkerPosition.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цвет маркера позиции.
        /// </summary>
        internal static string ColorMarkerPosition_DisplayName {
            get {
                return ResourceManager.GetString("ColorMarkerPosition.DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цвет фона выделенного маркера.
        /// </summary>
        internal static string ColorMarkerSelectedFill_Description {
            get {
                return ResourceManager.GetString("ColorMarkerSelectedFill.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фон выделенного.
        /// </summary>
        internal static string ColorMarkerSelectedFill_DisplayName {
            get {
                return ResourceManager.GetString("ColorMarkerSelectedFill.DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прозрачность фона выделенного маркера.
        /// </summary>
        internal static string ColorMarkerSelectedFillAlpha_Description {
            get {
                return ResourceManager.GetString("ColorMarkerSelectedFillAlpha.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прозрачность выделенного.
        /// </summary>
        internal static string ColorMarkerSelectedFillAlphaDisplayName {
            get {
                return ResourceManager.GetString("ColorMarkerSelectedFillAlphaDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цвет линий выделенного маркера.
        /// </summary>
        internal static string ColorMarkerSelectedLine_Description {
            get {
                return ResourceManager.GetString("ColorMarkerSelectedLine.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цвет линий выделенного.
        /// </summary>
        internal static string ColorMarkerSelectedLine_DisplayName {
            get {
                return ResourceManager.GetString("ColorMarkerSelectedLine.DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прозрачность линий выделенного маркера.
        /// </summary>
        internal static string ColorMarkerSelectedLineAlpha_Description {
            get {
                return ResourceManager.GetString("ColorMarkerSelectedLineAlpha.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прозрачность линий выделенного.
        /// </summary>
        internal static string ColorMarkerSelectedLineAlpha_DisplayName {
            get {
                return ResourceManager.GetString("ColorMarkerSelectedLineAlpha.DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цвет текста маркера.
        /// </summary>
        internal static string ColorMarkerText_Description {
            get {
                return ResourceManager.GetString("ColorMarkerText.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цвет текста.
        /// </summary>
        internal static string ColorMarkerText_DisplayName {
            get {
                return ResourceManager.GetString("ColorMarkerText.DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прозрачность текста маркера.
        /// </summary>
        internal static string ColorMarkerTextAlpha_Description {
            get {
                return ResourceManager.GetString("ColorMarkerTextAlpha.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прозрачность текста.
        /// </summary>
        internal static string ColorMarkerTextAlpha_DisplayName {
            get {
                return ResourceManager.GetString("ColorMarkerTextAlpha.DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цвет фона текста маркера.
        /// </summary>
        internal static string ColorMarkerTextFill_Description {
            get {
                return ResourceManager.GetString("ColorMarkerTextFill.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цвет фона текста.
        /// </summary>
        internal static string ColorMarkerTextFill_DisplayName {
            get {
                return ResourceManager.GetString("ColorMarkerTextFill.DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прозрачность фона текста маркера.
        /// </summary>
        internal static string ColorMarkerTextFillAlpha_Description {
            get {
                return ResourceManager.GetString("ColorMarkerTextFillAlpha.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прозрачность фона текста.
        /// </summary>
        internal static string ColorMarkerTextFillAlpha_DisplayName {
            get {
                return ResourceManager.GetString("ColorMarkerTextFillAlpha.DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цвет плитки кластера.
        /// </summary>
        internal static string ColorTileCluster_Description {
            get {
                return ResourceManager.GetString("ColorTileCluster.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кластер: цвет.
        /// </summary>
        internal static string ColorTileCluster_DisplayName {
            get {
                return ResourceManager.GetString("ColorTileCluster.DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прозрачность плитки кластера.
        /// </summary>
        internal static string ColorTileClusterAlpha_Description {
            get {
                return ResourceManager.GetString("ColorTileClusterAlpha.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кластер: прозрачность.
        /// </summary>
        internal static string ColorTileClusterAlpha_DisplayName {
            get {
                return ResourceManager.GetString("ColorTileClusterAlpha.DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прозрачность границы плитки кластера.
        /// </summary>
        internal static string ColorTileClusterLineAlpha_Description {
            get {
                return ResourceManager.GetString("ColorTileClusterLineAlpha.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кластер: прозрачность линии.
        /// </summary>
        internal static string ColorTileClusterLineAlpha_DisplayName {
            get {
                return ResourceManager.GetString("ColorTileClusterLineAlpha.DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цвет плитки в тепловой карте.
        /// </summary>
        internal static string ColorTileHeatmap_Description {
            get {
                return ResourceManager.GetString("ColorTileHeatmap.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тепловая карта: цвет.
        /// </summary>
        internal static string ColorTileHeatmap_DisplayName {
            get {
                return ResourceManager.GetString("ColorTileHeatmap.DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прозрачность границы плитки в тепловой карте.
        /// </summary>
        internal static string ColorTileHeatmapLineAlpha_Description {
            get {
                return ResourceManager.GetString("ColorTileHeatmapLineAlpha.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тепловая карта: прозрачность линии.
        /// </summary>
        internal static string ColorTileHeatmapLineAlpha_DisplayName {
            get {
                return ResourceManager.GetString("ColorTileHeatmapLineAlpha.DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Максимальная прозрачность плитки в тепловой карте.
        /// </summary>
        internal static string ColorTileHeatmapMaxAlpha_Description {
            get {
                return ResourceManager.GetString("ColorTileHeatmapMaxAlpha.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тепловая карта: максимальная прозрачность плитки.
        /// </summary>
        internal static string ColorTileHeatmapMaxAlpha_DisplayName {
            get {
                return ResourceManager.GetString("ColorTileHeatmapMaxAlpha.DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Минимальная прозрачность плитки в тепловой карте.
        /// </summary>
        internal static string ColorTileHeatmapMinAlpha_Description {
            get {
                return ResourceManager.GetString("ColorTileHeatmapMinAlpha.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тепловая карта: минимальная прозрачность плитки.
        /// </summary>
        internal static string ColorTileHeatmapMinAlpha_DisplayName {
            get {
                return ResourceManager.GetString("ColorTileHeatmapMinAlpha.DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цвет плиток максимального кластера.
        /// </summary>
        internal static string ColorTileMaxCluster_Description {
            get {
                return ResourceManager.GetString("ColorTileMaxCluster.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Максимальный кластер: цвет.
        /// </summary>
        internal static string ColorTileMaxCluster_DisplayName {
            get {
                return ResourceManager.GetString("ColorTileMaxCluster.DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прозрачность плиток максимального кластера.
        /// </summary>
        internal static string ColorTileMaxClusterAlpha_Description {
            get {
                return ResourceManager.GetString("ColorTileMaxClusterAlpha.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Максимальный кластер: прозрачность.
        /// </summary>
        internal static string ColorTileMaxClusterAlpha_DisplayName {
            get {
                return ResourceManager.GetString("ColorTileMaxClusterAlpha.DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прозрачность границ плиток максимального кластера.
        /// </summary>
        internal static string ColorTileMaxClusterLineAlpha_Description {
            get {
                return ResourceManager.GetString("ColorTileMaxClusterLineAlpha.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Максимальный кластер: прозрачность линии.
        /// </summary>
        internal static string ColorTileMaxClusterLineAlpha_DisplayName {
            get {
                return ResourceManager.GetString("ColorTileMaxClusterLineAlpha.DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цвет плиток квадрата.
        /// </summary>
        internal static string ColorTileMaxSquare_Description {
            get {
                return ResourceManager.GetString("ColorTileMaxSquare.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Квадрат: цвет.
        /// </summary>
        internal static string ColorTileMaxSquare_DisplayName {
            get {
                return ResourceManager.GetString("ColorTileMaxSquare.DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прозрачность плиток квадрата.
        /// </summary>
        internal static string ColorTileMaxSquareAlpha_Description {
            get {
                return ResourceManager.GetString("ColorTileMaxSquareAlpha.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Квадрат: прозрачность.
        /// </summary>
        internal static string ColorTileMaxSquareAlpha_DisplayName {
            get {
                return ResourceManager.GetString("ColorTileMaxSquareAlpha.DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прозрачность границ плиток квадрата.
        /// </summary>
        internal static string ColorTileMaxSquareLineAlpha_Description {
            get {
                return ResourceManager.GetString("ColorTileMaxSquareLineAlpha.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Квадрат: прозрачность линии.
        /// </summary>
        internal static string ColorTileMaxSquareLineAlpha_DisplayName {
            get {
                return ResourceManager.GetString("ColorTileMaxSquareLineAlpha.DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цвет плитки выбранного трека.
        /// </summary>
        internal static string ColorTileTrackSelected_Description {
            get {
                return ResourceManager.GetString("ColorTileTrackSelected.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбранный трек: цвет.
        /// </summary>
        internal static string ColorTileTrackSelected_DisplayName {
            get {
                return ResourceManager.GetString("ColorTileTrackSelected.DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прозрачность плитки выбранного трека.
        /// </summary>
        internal static string ColorTileTrackSelectedAlpha_Description {
            get {
                return ResourceManager.GetString("ColorTileTrackSelectedAlpha.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбранный трек: прозрачность.
        /// </summary>
        internal static string ColorTileTrackSelectedAlpha_DisplayName {
            get {
                return ResourceManager.GetString("ColorTileTrackSelectedAlpha.DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прозрачность границы плитки выбранного трека.
        /// </summary>
        internal static string ColorTileTrackSelectedLineAlpha_Description {
            get {
                return ResourceManager.GetString("ColorTileTrackSelectedLineAlpha.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбранный трек: прозрачность границы.
        /// </summary>
        internal static string ColorTileTrackSelectedLineAlpha_DisplayName {
            get {
                return ResourceManager.GetString("ColorTileTrackSelectedLineAlpha.DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цвет открытых плиток.
        /// </summary>
        internal static string ColorTileVisited_Description {
            get {
                return ResourceManager.GetString("ColorTileVisited.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Открытая: цвет.
        /// </summary>
        internal static string ColorTileVisited_DisplayName {
            get {
                return ResourceManager.GetString("ColorTileVisited.DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прозрачность открытых плиток.
        /// </summary>
        internal static string ColorTileVisitedAlpha_Description {
            get {
                return ResourceManager.GetString("ColorTileVisitedAlpha.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Открытая: прозрачность.
        /// </summary>
        internal static string ColorTileVisitedAlpha_DisplayName {
            get {
                return ResourceManager.GetString("ColorTileVisitedAlpha.DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прозрачность границ открытых плиток.
        /// </summary>
        internal static string ColorTileVisitedLineAlpha_Description {
            get {
                return ResourceManager.GetString("ColorTileVisitedLineAlpha.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Открытая: прозрачность линии.
        /// </summary>
        internal static string ColorTileVisitedLineAlpha_DisplayName {
            get {
                return ResourceManager.GetString("ColorTileVisitedLineAlpha.DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цвет трека.
        /// </summary>
        internal static string ColorTrack_Description {
            get {
                return ResourceManager.GetString("ColorTrack.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цвет.
        /// </summary>
        internal static string ColorTrack_DisplayName {
            get {
                return ResourceManager.GetString("ColorTrack.DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прозрачность трека.
        /// </summary>
        internal static string ColorTrackAlpha_Description {
            get {
                return ResourceManager.GetString("ColorTrackAlpha.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прозрачность.
        /// </summary>
        internal static string ColorTrackAlpha_DisplayName {
            get {
                return ResourceManager.GetString("ColorTrackAlpha.DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цвет выбранного трека.
        /// </summary>
        internal static string ColorTrackSelected_Description {
            get {
                return ResourceManager.GetString("ColorTrackSelected.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цвет выбранного.
        /// </summary>
        internal static string ColorTrackSelected_DisplayName {
            get {
                return ResourceManager.GetString("ColorTrackSelected.DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прозрачность выбранного трека.
        /// </summary>
        internal static string ColorTrackSelectedAlpha_Description {
            get {
                return ResourceManager.GetString("ColorTrackSelectedAlpha.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прозрачность выбранного.
        /// </summary>
        internal static string ColorTrackSelectedAlpha_DisplayName {
            get {
                return ResourceManager.GetString("ColorTrackSelectedAlpha.DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Расположение файла базы данных. Пустое значение — \AppData\Roaming\TileExplorer\.
        /// </summary>
        internal static string DirectoryDatabase_Description {
            get {
                return ResourceManager.GetString("DirectoryDatabase.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to База данных.
        /// </summary>
        internal static string DirectoryDatabase_DisplayName {
            get {
                return ResourceManager.GetString("DirectoryDatabase.DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Каталог с общими для всех компьютеров настройками.
        /// </summary>
        internal static string DirectoryRoaming_Description {
            get {
                return ResourceManager.GetString("DirectoryRoaming.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Общие настройки.
        /// </summary>
        internal static string DirectoryRoaming_DisplayName {
            get {
                return ResourceManager.GetString("DirectoryRoaming.DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Расположение каталога с треками. Пустое значение — поиск новых треков отключен..
        /// </summary>
        internal static string DirectoryTracks_Description {
            get {
                return ResourceManager.GetString("DirectoryTracks.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Треки.
        /// </summary>
        internal static string DirectoryTracks_DisplayName {
            get {
                return ResourceManager.GetString("DirectoryTracks.DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Шрифт маркера.
        /// </summary>
        internal static string FontMarker_Description {
            get {
                return ResourceManager.GetString("FontMarker.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Шрифт.
        /// </summary>
        internal static string FontMarker_DisplayName {
            get {
                return ResourceManager.GetString("FontMarker.DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Формат даты.
        /// </summary>
        internal static string FormatDate_Description {
            get {
                return ResourceManager.GetString("FormatDate.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата.
        /// </summary>
        internal static string FormatDate_DisplayName {
            get {
                return ResourceManager.GetString("FormatDate.DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Формат даты и времени.
        /// </summary>
        internal static string FormatDateTime_Description {
            get {
                return ResourceManager.GetString("FormatDateTime.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата и время.
        /// </summary>
        internal static string FormatDateTime_DisplayName {
            get {
                return ResourceManager.GetString("FormatDateTime.DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Формат расстояний.
        /// </summary>
        internal static string FormatDistance_Description {
            get {
                return ResourceManager.GetString("FormatDistance.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Расстояние.
        /// </summary>
        internal static string FormatDistance_DisplayName {
            get {
                return ResourceManager.GetString("FormatDistance.DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Формат расстояний (округлённое значение).
        /// </summary>
        internal static string FormatDistance2_Description {
            get {
                return ResourceManager.GetString("FormatDistance2.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Расстояние (км).
        /// </summary>
        internal static string FormatDistance2_DisplayName {
            get {
                return ResourceManager.GetString("FormatDistance2.DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Формат подъёма.
        /// </summary>
        internal static string FormatEleAscent_Description {
            get {
                return ResourceManager.GetString("FormatEleAscent.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подъём.
        /// </summary>
        internal static string FormatEleAscent_DisplayName {
            get {
                return ResourceManager.GetString("FormatEleAscent.DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Формат подъёмов (округлённое значение).
        /// </summary>
        internal static string FormatEleAscent2_Description {
            get {
                return ResourceManager.GetString("FormatEleAscent2.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подъём (м).
        /// </summary>
        internal static string FormatEleAscent2_DisplayName {
            get {
                return ResourceManager.GetString("FormatEleAscent2.DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Формат координат.
        /// </summary>
        internal static string FormatLatLng_Description {
            get {
                return ResourceManager.GetString("FormatLatLng.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Координаты.
        /// </summary>
        internal static string FormatLatLng_DisplayName {
            get {
                return ResourceManager.GetString("FormatLatLng.DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Формат времени.
        /// </summary>
        internal static string FormatTime_Description {
            get {
                return ResourceManager.GetString("FormatTime.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Время.
        /// </summary>
        internal static string FormatTime_DisplayName {
            get {
                return ResourceManager.GetString("FormatTime.DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ключ линии сетки.
        /// </summary>
        internal static string OsmTileKey_Description {
            get {
                return ResourceManager.GetString("OsmTileKey.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ключ.
        /// </summary>
        internal static string OsmTileKey_DisplayName {
            get {
                return ResourceManager.GetString("OsmTileKey.DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Значение ключа линии сетки.
        /// </summary>
        internal static string OsmTileValue_Description {
            get {
                return ResourceManager.GetString("OsmTileValue.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Значение.
        /// </summary>
        internal static string OsmTileValue_DisplayName {
            get {
                return ResourceManager.GetString("OsmTileValue.DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Минимальный масштаб сетки.
        /// </summary>
        internal static string SaveOsmTileMinZoom_Description {
            get {
                return ResourceManager.GetString("SaveOsmTileMinZoom.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Минимальный масштаб.
        /// </summary>
        internal static string SaveOsmTileMinZoom_DisplayName {
            get {
                return ResourceManager.GetString("SaveOsmTileMinZoom.DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Значок точки.
        /// </summary>
        internal static string TileStatusFileOsmandIcon_Description {
            get {
                return ResourceManager.GetString("TileStatusFileOsmandIcon.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Значок.
        /// </summary>
        internal static string TileStatusFileOsmandIcon_DisplayName {
            get {
                return ResourceManager.GetString("TileStatusFileOsmandIcon.DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип значка точки.
        /// </summary>
        internal static string TileStatusFileOsmandIconBackground_Description {
            get {
                return ResourceManager.GetString("TileStatusFileOsmandIconBackground.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип значка.
        /// </summary>
        internal static string TileStatusFileOsmandIconBackground_DisplayName {
            get {
                return ResourceManager.GetString("TileStatusFileOsmandIconBackground.DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цвет значка точки.
        /// </summary>
        internal static string TileStatusFileOsmandIconColor_Description {
            get {
                return ResourceManager.GetString("TileStatusFileOsmandIconColor.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цвет значка.
        /// </summary>
        internal static string TileStatusFileOsmandIconColor_DisplayName {
            get {
                return ResourceManager.GetString("TileStatusFileOsmandIconColor.DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить информацию для Османда.
        /// </summary>
        internal static string TileStatusFileUseOsmand_Description {
            get {
                return ResourceManager.GetString("TileStatusFileUseOsmand.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Информация для Османда.
        /// </summary>
        internal static string TileStatusFileUseOsmand_DisplayName {
            get {
                return ResourceManager.GetString("TileStatusFileUseOsmand.DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип точки.
        /// </summary>
        internal static string TileStatusFileWptType_Description {
            get {
                return ResourceManager.GetString("TileStatusFileWptType.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип точки.
        /// </summary>
        internal static string TileStatusFileWptType_DisplayName {
            get {
                return ResourceManager.GetString("TileStatusFileWptType.DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Толщина линий маркера.
        /// </summary>
        internal static string WidthMarkerLine_Description {
            get {
                return ResourceManager.GetString("WidthMarkerLine.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Толщина линий.
        /// </summary>
        internal static string WidthMarkerLine_DisplayName {
            get {
                return ResourceManager.GetString("WidthMarkerLine.DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Толщина линий выделенного маркера.
        /// </summary>
        internal static string WidthMarkerLineSelected_Description {
            get {
                return ResourceManager.GetString("WidthMarkerLineSelected.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Толщина линий выделенного.
        /// </summary>
        internal static string WidthMarkerLineSelected_DisplayName {
            get {
                return ResourceManager.GetString("WidthMarkerLineSelected.DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Толщина трека.
        /// </summary>
        internal static string WidthTrack_Description {
            get {
                return ResourceManager.GetString("WidthTrack.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Толщина.
        /// </summary>
        internal static string WidthTrack_DisplayName {
            get {
                return ResourceManager.GetString("WidthTrack.DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Толщина выделенного трека.
        /// </summary>
        internal static string WidthTrackSelected_Description {
            get {
                return ResourceManager.GetString("WidthTrackSelected.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Толщина выделенного.
        /// </summary>
        internal static string WidthTrackSelected_DisplayName {
            get {
                return ResourceManager.GetString("WidthTrackSelected.DisplayName", resourceCulture);
            }
        }
    }
}
