//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TileExplorer.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.5.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool VisibleMarkers {
            get {
                return ((bool)(this["VisibleMarkers"]));
            }
            set {
                this["VisibleMarkers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LightGray")]
        public global::System.Drawing.Color ColorMarkerTextFill {
            get {
                return ((global::System.Drawing.Color)(this["ColorMarkerTextFill"]));
            }
            set {
                this["ColorMarkerTextFill"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("220")]
        public byte ColorMarkerTextFillAlpha {
            get {
                return ((byte)(this["ColorMarkerTextFillAlpha"]));
            }
            set {
                this["ColorMarkerTextFillAlpha"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Gray")]
        public global::System.Drawing.Color ColorMarkerLine {
            get {
                return ((global::System.Drawing.Color)(this["ColorMarkerLine"]));
            }
            set {
                this["ColorMarkerLine"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("240")]
        public byte ColorMarkerLineAlpha {
            get {
                return ((byte)(this["ColorMarkerLineAlpha"]));
            }
            set {
                this["ColorMarkerLineAlpha"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Green")]
        public global::System.Drawing.Color ColorMarkerText {
            get {
                return ((global::System.Drawing.Color)(this["ColorMarkerText"]));
            }
            set {
                this["ColorMarkerText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255")]
        public byte ColorMarkerTextAlpha {
            get {
                return ((byte)(this["ColorMarkerTextAlpha"]));
            }
            set {
                this["ColorMarkerTextAlpha"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public global::System.Drawing.Color ColorTileVisited {
            get {
                return ((global::System.Drawing.Color)(this["ColorTileVisited"]));
            }
            set {
                this["ColorTileVisited"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("25")]
        public byte ColorTileVisitedAlpha {
            get {
                return ((byte)(this["ColorTileVisitedAlpha"]));
            }
            set {
                this["ColorTileVisitedAlpha"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("GreenYellow")]
        public global::System.Drawing.Color ColorTileCluster {
            get {
                return ((global::System.Drawing.Color)(this["ColorTileCluster"]));
            }
            set {
                this["ColorTileCluster"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40")]
        public byte ColorTileClusterAlpha {
            get {
                return ((byte)(this["ColorTileClusterAlpha"]));
            }
            set {
                this["ColorTileClusterAlpha"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Green")]
        public global::System.Drawing.Color ColorTileMaxCluster {
            get {
                return ((global::System.Drawing.Color)(this["ColorTileMaxCluster"]));
            }
            set {
                this["ColorTileMaxCluster"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40")]
        public byte ColorTileMaxClusterAlpha {
            get {
                return ((byte)(this["ColorTileMaxClusterAlpha"]));
            }
            set {
                this["ColorTileMaxClusterAlpha"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Blue")]
        public global::System.Drawing.Color ColorTileMaxSquare {
            get {
                return ((global::System.Drawing.Color)(this["ColorTileMaxSquare"]));
            }
            set {
                this["ColorTileMaxSquare"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40")]
        public byte ColorTileMaxSquareAlpha {
            get {
                return ((byte)(this["ColorTileMaxSquareAlpha"]));
            }
            set {
                this["ColorTileMaxSquareAlpha"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("25")]
        public byte ColorTileVisitedLineAlpha {
            get {
                return ((byte)(this["ColorTileVisitedLineAlpha"]));
            }
            set {
                this["ColorTileVisitedLineAlpha"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("80")]
        public byte ColorTileClusterLineAlpha {
            get {
                return ((byte)(this["ColorTileClusterLineAlpha"]));
            }
            set {
                this["ColorTileClusterLineAlpha"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("80")]
        public byte ColorTileMaxClusterLineAlpha {
            get {
                return ((byte)(this["ColorTileMaxClusterLineAlpha"]));
            }
            set {
                this["ColorTileMaxClusterLineAlpha"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("80")]
        public byte ColorTileMaxSquareLineAlpha {
            get {
                return ((byte)(this["ColorTileMaxSquareLineAlpha"]));
            }
            set {
                this["ColorTileMaxSquareLineAlpha"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Arial, 10pt")]
        public global::System.Drawing.Font FontMarker {
            get {
                return ((global::System.Drawing.Font)(this["FontMarker"]));
            }
            set {
                this["FontMarker"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Green")]
        public global::System.Drawing.Color ColorMarkerFill {
            get {
                return ((global::System.Drawing.Color)(this["ColorMarkerFill"]));
            }
            set {
                this["ColorMarkerFill"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("220")]
        public byte ColorMarkerFillAlpha {
            get {
                return ((byte)(this["ColorMarkerFillAlpha"]));
            }
            set {
                this["ColorMarkerFillAlpha"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool VisibleTracks {
            get {
                return ((bool)(this["VisibleTracks"]));
            }
            set {
                this["VisibleTracks"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public global::System.Drawing.Color ColorTrack {
            get {
                return ((global::System.Drawing.Color)(this["ColorTrack"]));
            }
            set {
                this["ColorTrack"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("144")]
        public byte ColorTrackAlpha {
            get {
                return ((byte)(this["ColorTrackAlpha"]));
            }
            set {
                this["ColorTrackAlpha"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public float WidthTrack {
            get {
                return ((float)(this["WidthTrack"]));
            }
            set {
                this["WidthTrack"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int TrackMinDistancePoint {
            get {
                return ((int)(this["TrackMinDistancePoint"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool VisibleListMarkers {
            get {
                return ((bool)(this["VisibleListMarkers"]));
            }
            set {
                this["VisibleListMarkers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool VisibleListTracks {
            get {
                return ((bool)(this["VisibleListTracks"]));
            }
            set {
                this["VisibleListTracks"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DarkSlateBlue")]
        public global::System.Drawing.Color ColorMarkerSelectedLine {
            get {
                return ((global::System.Drawing.Color)(this["ColorMarkerSelectedLine"]));
            }
            set {
                this["ColorMarkerSelectedLine"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public float WidthTrackSelected {
            get {
                return ((float)(this["WidthTrackSelected"]));
            }
            set {
                this["WidthTrackSelected"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public float WidthMarkerLineSelected {
            get {
                return ((float)(this["WidthMarkerLineSelected"]));
            }
            set {
                this["WidthMarkerLineSelected"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float WidthMarkerLine {
            get {
                return ((float)(this["WidthMarkerLine"]));
            }
            set {
                this["WidthMarkerLine"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DarkSlateBlue")]
        public global::System.Drawing.Color ColorMarkerSelectedFill {
            get {
                return ((global::System.Drawing.Color)(this["ColorMarkerSelectedFill"]));
            }
            set {
                this["ColorMarkerSelectedFill"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DarkSlateBlue")]
        public global::System.Drawing.Color ColorTrackSelected {
            get {
                return ((global::System.Drawing.Color)(this["ColorTrackSelected"]));
            }
            set {
                this["ColorTrackSelected"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MapGrayScale {
            get {
                return ((bool)(this["MapGrayScale"]));
            }
            set {
                this["MapGrayScale"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("51.196369")]
        public double HomeLat {
            get {
                return ((double)(this["HomeLat"]));
            }
            set {
                this["HomeLat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("58.298527")]
        public double HomeLng {
            get {
                return ((double)(this["HomeLng"]));
            }
            set {
                this["HomeLng"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("11")]
        public int HomeZoom {
            get {
                return ((int)(this["HomeZoom"]));
            }
            set {
                this["HomeZoom"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.00")]
        public string FormatDistance {
            get {
                return ((string)(this["FormatDistance"]));
            }
            set {
                this["FormatDistance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("yyyy.MM.dd HH:mm")]
        public string FormatDateTime {
            get {
                return ((string)(this["FormatDateTime"]));
            }
            set {
                this["FormatDateTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.000000")]
        public string FormatLatLng {
            get {
                return ((string)(this["FormatLatLng"]));
            }
            set {
                this["FormatLatLng"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool VisibleFilter {
            get {
                return ((bool)(this["VisibleFilter"]));
            }
            set {
                this["VisibleFilter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("yyyy.MM.dd")]
        public string FormatDate {
            get {
                return ((string)(this["FormatDate"]));
            }
            set {
                this["FormatDate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime FilterDay {
            get {
                return ((global::System.DateTime)(this["FilterDay"]));
            }
            set {
                this["FilterDay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime FilterDateFrom {
            get {
                return ((global::System.DateTime)(this["FilterDateFrom"]));
            }
            set {
                this["FilterDateFrom"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime FilterDateTo {
            get {
                return ((global::System.DateTime)(this["FilterDateTo"]));
            }
            set {
                this["FilterDateTo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FilterYears {
            get {
                return ((string)(this["FilterYears"]));
            }
            set {
                this["FilterYears"] = value;
            }
        }
    }
}
